# ---------------------------------------------------------
# 1. BACKEND (API Rocket League)
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-app
  namespace: user-morgannder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rocket-league
  template:
    metadata:
      labels:
        app: rocket-league
    spec:
      containers:
      - name: web
        image: docker.io/meaumeau/ensai2a-cl-rlstatsanalysis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: rocket-config
        - secretRef:
            name: rocket-secrets
        volumeMounts:
        - name: db-storage
          mountPath: /app/src/database
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: rocket-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-app-service
  namespace: user-morgannder
spec:
  selector:
    app: rocket-league
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-app-ingress
  namespace: user-morgannder
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rocketcl.api.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocket-app-service
            port:
              number: 8000

---
# ---------------------------------------------------------
# 2. FRONTEND (Interface Vite)
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-frontend
  namespace: user-morgannder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-frontend
  template:
    metadata:
      labels:
        app: rocket-frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/meaumeau/ensai2a-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-frontend-service
  namespace: user-morgannder
spec:
  selector:
    app: rocket-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-frontend-ingress
  namespace: user-morgannder
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rocketclstats.api.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocket-frontend-service
            port:
              number: 80
