apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-league
  template:
    metadata:
      labels:
        app: rocket-league
    spec:
      containers:
      - name: web
        image: docker.io/meaumeau/ensai2a-cl-rlstatsanalysis:latest
        ports:
        - containerPort: 8000
        envFrom: # On injecte tout le contenu des deux fichiers
        - configMapRef:
            name: rocket-config
        - secretRef:
            name: rocket-secrets
