# ==========================================
# 1. Ingress pour le Backend
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-ingress
  namespace: user-morgannder
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: rocketcl.api.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocket-app-service
            port:
              number: 8000
---
# ==========================================
# 2. Ingress pour le Frontend
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-frontend-ingress
  namespace: user-morgannder
spec:
  ingressClassName: nginx
  rules:
  - host: rocketclstats.api.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocket-frontend-service
            port:
              number: 80
