MOVEMENT_AGGREGATED_BY_RANK_DATA_EXAMPLE = {
    "game_mode": "ranked-doubles",
    "rank": "Bronze",
    "stats_type": "movement",
    "data": {
        "avg_speed": 1308.71,
        "total_distance": 291179.65,
        "time_supersonic_speed": 15.89,
        "time_boost_speed": 74.62,
        "time_slow_speed": 164.49,
        "time_ground": 171.02,
        "time_low_air": 76.58,
        "time_high_air": 7.4,
        "time_powerslide": 2.25,
        "count_powerslide": 12.06,
        "avg_powerslide_duration": 0.21,
        "avg_speed_percentage": 56.9,
        "percent_slow_speed": 63.52,
        "percent_boost_speed": 29.87,
        "percent_supersonic_speed": 6.61,
        "percent_ground": 65.72,
        "percent_low_air": 30.81,
        "percent_high_air": 3.47,
    },
}

MOVEMENT_AGGREGATED_PLAYER_DATA_EXAMPLE = {
    "game_mode": "ranked-doubles",
    "platform_id": "id",
    "stats_type": "movement",
    "data": {
        "avg_speed": 1357,
        "total_distance": 488111,
        "time_supersonic_speed": 30.01,
        "time_boost_speed": 143.32,
        "time_slow_speed": 210.25,
        "time_ground": 248.25,
        "time_low_air": 129.49,
        "time_high_air": 5.84,
        "time_powerslide": 5.89,
        "count_powerslide": 30,
        "avg_powerslide_duration": 0.2,
        "avg_speed_percentage": 59,
        "percent_slow_speed": 55.03,
        "percent_boost_speed": 37.22,
        "percent_supersonic_speed": 7.75,
        "percent_ground": 64.69,
        "percent_low_air": 33.82,
        "percent_high_air": 1.5,
    },
}


MOVEMENT_AGGREGATED_BY_MATCH_DATA_EXAMPLE = {
    "game_mode": "ranked-doubles",
    "platform_id": "id_1",
    "match_id": "id_2",
    "stats_type": "movement",
    "data": {
        "participation_id": 1,
        "avg_speed": 1387,
        "total_distance": 556450,
        "time_supersonic_speed": 36.06,
        "time_boost_speed": 166.33,
        "time_slow_speed": 231.66,
        "time_ground": 281.92,
        "time_low_air": 144.84,
        "time_high_air": 7.29,
        "time_powerslide": 5.21,
        "count_powerslide": 26,
        "avg_powerslide_duration": 0.2,
        "avg_speed_percentage": 60.304348,
        "percent_slow_speed": 53.371735,
        "percent_boost_speed": 38.320473,
        "percent_supersonic_speed": 8.307799,
        "percent_ground": 64.95104,
        "percent_low_air": 33.369427,
        "percent_high_air": 1.6795299,
    },
}
