class StatsPositioning:
    def __init__(
        self,
        participation_id: int = 0,
        average_distance_to_ball: int = 0,
        average_distance_to_ball_possession: int = 0,
        average_distance_to_ball_no_possession: int = 0,
        average_distance_to_mates: int = 0,
        time_defensive_third: float = 0.0,
        time_neutral_third: float = 0.0,
        time_offensive_third: float = 0.0,
        time_defensive_half: float = 0.0,
        time_offensive_half: float = 0.0,
        time_behind_ball: float = 0.0,
        time_infront_ball: float = 0.0,
        time_most_back: float = 0.0,
        time_most_forward: float = 0.0,
        goals_against_while_last_defender: int = 0,
        time_closest_to_ball: float = 0.0,
        time_farthest_to_ball: float = 0.0,
        percent_defensive_third: float = 0.0,
        percent_neutral_third: float = 0.0,
        percent_offensive_third: float = 0.0,
        percent_defensive_half: float = 0.0,
        percent_offensive_half: float = 0.0,
        percent_behind_ball: float = 0.0,
        percent_infront_ball: float = 0.0,
        percent_most_back: float = 0.0,
        percent_most_forward: float = 0.0,
        percent_closest_to_ball: float = 0.0,
        percent_farthest_from_ball: float = 0.0,
    ):
        pass
