class StatsBoost:
    def __init__(
        self,
        participation_id: int = 0,
        boost_per_minute: float = 0.0,
        boost_consumed_per_minute: float = 0.0,
        average_amount: float = 0.0,
        amount_collected: int = 0,
        amount_stolen: int = 0,
        amount_collected_big: int = 0,
        amount_stolen_big: int = 0,
        amount_collected_small: int = 0,
        amount_stolen_small: int = 0,
        count_collected_big: int = 0,
        count_stolen_big: int = 0,
        count_collected_small: int = 0,
        count_stolen_small: int = 0,
        amount_overfill: int = 0,
        amount_overfill_stolen: int = 0,
        amount_used_while_supersonic: int = 0,
        time_zero_boost: float = 0.0,
        percent_zero_boost: float = 0.0,
        time_full_boost: float = 0.0,
        percent_full_boost: float = 0.0,
        time_boost_0_25: float = 0.0,
        time_boost_25_50: float = 0.0,
        time_boost_50_75: float = 0.0,
        time_boost_75_100: float = 0.0,
        percent_boost_0_25: float = 0.0,
        percent_boost_25_50: float = 0.0,
        percent_boost_50_75: float = 0.0,
        percent_boost_75_100: float = 0.0,
    ):
        pass
