name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ] # Se déclenche sur les pushs vers develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: meaumeau/ensai2a-cl-rlstatsanalysis:latest

      - name: Build and Push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64
          tags: meaumeau/ensai2a-frontend:latest

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          # On applique les fichiers YAML (Deployment, Service, Ingress)
          kubectl apply -f src/kubernetes/ -n user-morgannder # Dans ton namespace

          # On force le redémarrage pour utiliser les nouvelles images
          kubectl rollout restart deployment rocket-app -n user-morgannder
          kubectl rollout restart deployment rocket-frontend -n user-morgannder
